site_name: mlscat
site_author: M0nk3y

theme:
  name: "material"

plugins:
  - search
nav:
  - Home: index.md

  - API:
      - Attack: attack.md
      - Data_Loader: data.md
      - Leakage: leakage.md
      - Metrics: metrics.md
      - Security: security.md
      - utils: utils.md
  - Quickstart:
      - Quickstart: quickstart.md
      - CPA攻击: quickstart#_1
